services:
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3001"
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - ./frontend/.env.local

  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /app/__pycache__
    ports:
      - "8001:8000"
    env_file:
      - ./backend/.env