/**
 * Excel function argument type mappings
 * Maps function names to their argument type signatures
 */

export const EXCEL_FUNCTION_SIGNATURES: Record<string, string> = {
  ABS: 'number',
  ACOS: 'number',
  ACOSH: 'number',
  ACOT: 'number',
  ACOTH: 'number',
  ADDRESS: 'row_num, column_num, [abs_num], [a1], [sheet_text]',
  AGGREGATE: 'function_num, options, array, [k]',
  AND: 'logical1, [logical2], ...',
  ARABIC: 'text',
  AREAS: 'reference',
  ASIN: 'number',
  ASINH: 'number',
  ATAN: 'number',
  ATAN2: 'x_num, y_num',
  ATANH: 'number',

  AVERAGE: 'number1, [number2], ...',
  AVERAGEA: 'value1, [value2], ...',
  AVERAGEIF: 'range, criteria, [average_range]',
  AVERAGEIFS: 'average_range, criteria_range1, criteria1, [criteria_range2], [criteria2], ...',

  BASE: 'number, radix, [min_length]',
  BESSELI: 'x, n',
  BESSELJ: 'x, n',
  BESSELK: 'x, n',
  BESSELY: 'x, n',
  BETADIST: 'x, alpha, beta, [A], [B]',
  BETAINV: 'probability, alpha, beta, [A], [B]',
  BIN2DEC: 'number',
  BIN2HEX: 'number, [places]',
  BIN2OCT: 'number, [places]',
  BITAND: 'number1, number2',
  BITLSHIFT: 'number, shift_amount',
  BITOR: 'number1, number2',
  BITRSHIFT: 'number, shift_amount',
  BITXOR: 'number1, number2',

  CEILING: 'number, significance',
  'CEILING.MATH': 'number, [significance], [mode]',
  'CEILING.PRECISE': 'number, [significance]',
  CELL: 'info_type, [reference]',
  CHAR: 'number',
  'CHISQ.DIST': 'x, deg_freedom, cumulative',
  'CHISQ.DIST.RT': 'x, deg_freedom',
  'CHISQ.INV': 'probability, deg_freedom',
  'CHISQ.INV.RT': 'probability, deg_freedom',
  'CHISQ.TEST': 'actual_range, expected_range',
  CHOOSE: 'index_num, value1, [value2], ...',
  CHOOSECOLS: 'array, col_num1, [col_num2], ...',
  CHOOSEROWS: 'array, row_num1, [row_num2], ...',
  CLEAN: 'text',
  CODE: 'text',
  COLUMN: '[reference]',
  COLUMNS: 'array',
  COMBIN: 'number, number_chosen',
  COMBINA: 'number, number_chosen',
  COMPLEX: 'real_num, i_num, [suffix]',
  CONCAT: 'text1, [text2], ...',
  CONCATENATE: 'text1, [text2], ...',
  'CONFIDENCE.NORM': 'alpha, standard_dev, size',
  'CONFIDENCE.T': 'alpha, standard_dev, size',
  CONVERT: 'number, from_unit, to_unit',
  CORREL: 'array1, array2',
  COS: 'number',
  COSH: 'number',
  COT: 'number',
  COTH: 'number',
  COUNT: 'value1, [value2], ...',
  COUNTA: 'value1, [value2], ...',
  COUNTBLANK: 'range',
  COUNTIF: 'range, criteria',
  COUNTIFS: 'criteria_range1, criteria1, [criteria_range2], [criteria2], ...',
  COUPDAYBS: 'settlement, maturity, frequency, [basis]',
  COUPDAYS: 'settlement, maturity, frequency, [basis]',
  'COVARIANCE.P': 'array1, array2',
  'COVARIANCE.S': 'array1, array2',
  CSC: 'number',
  CSCH: 'number',

  DATE: 'year, month, day',
  DATEDIF: 'start_date, end_date, unit',
  DATEVALUE: 'date_text',
  DAVERAGE: 'database, field, criteria',
  DAY: 'serial_number',
  DAYS: 'end_date, start_date',
  DAYS360: 'start_date, end_date, [method]',
  DB: 'cost, salvage, life, period, [month]',
  DCOUNT: 'database, field, criteria',
  DCOUNTA: 'database, field, criteria',
  DEC2BIN: 'number, [places]',
  DEC2HEX: 'number, [places]',
  DEC2OCT: 'number, [places]',
  DECIMAL: 'text, radix',
  DEGREES: 'angle',
  DELTA: 'number1, [number2]',
  'DEV.SQ': 'number1, [number2], ...',
  DGET: 'database, field, criteria',
  DISC: 'settlement, maturity, pr, redemption, [basis]',
  DMAX: 'database, field, criteria',
  DMIN: 'database, field, criteria',
  DOLLAR: 'number, decimals',
  DROP: 'array, rows, [columns]',
  DSUM: 'database, field, criteria',
  DURATION: 'settlement, maturity, coupon, yld, frequency, [basis]',

  EDATE: 'start_date, months',
  EFFECT: 'nominal_rate, npery',
  EOMONTH: 'start_date, months',
  ERF: 'lower_limit, [upper_limit]',
  ERFC: 'x',
  EVEN: 'number',
  EXACT: 'text1, text2',
  EXP: 'number',

  'F.DIST': 'x, deg_freedom1, deg_freedom2, cumulative',
  'F.DIST.RT': 'x, deg_freedom1, deg_freedom2',
  'F.INV': 'probability, deg_freedom1, deg_freedom2',
  'F.INV.RT': 'probability, deg_freedom1, deg_freedom2',
  'F.TEST': 'array1, array2',
  FACT: 'number',
  FACTDOUBLE: 'number',
  FALSE: '',
  FILTER: 'array, include, [if_empty]',
  FIND: 'find_text, within_text, [start_num]',
  FISHER: 'x',
  FISHERINV: 'y',
  FIXED: 'number, [decimals], [no_commas]',
  FLOOR: 'number, significance',
  'FLOOR.MATH': 'number, [significance], [mode]',
  'FLOOR.PRECISE': 'number, [significance]',
  'FORECAST.LINEAR': 'x, known_y\'s, known_x\'s',
  FORMULATEXT: 'reference',
  FREQUENCY: 'data_array, bins_array',

  GAMMA: 'number',
  'GAMMA.DIST': 'x, alpha, beta, cumulative',
  'GAMMA.INV': 'probability, alpha, beta',
  GAMMALN: 'number',

  HLOOKUP: 'lookup_value, table_array, row_index_num, [range_lookup]',
  HOUR: 'serial_number',
  HSTACK: 'array1, [array2], ...',
  HYPERLINK: 'link_location, [friendly_name]',

  IF: 'logical_test, value_if_true, value_if_false',
  IFERROR: 'value, value_if_error',
  IFNA: 'value, value_if_na',
  IFS: 'logical_test1, value_if_true1, [logical_test2], [value_if_true2], ...',
  INDEX: 'array, row_num, [column_num]',
  INDIRECT: 'ref_text, [a1]',
  INT: 'number',
  INTERCEPT: 'known_y\'s, known_x\'s',
  ISBLANK: 'value',
  ISERR: 'value',
  ISERROR: 'value',
  ISEVEN: 'number',
  ISLOGICAL: 'value',
  ISNA: 'value',
  ISNONTEXT: 'value',
  ISNUMBER: 'value',
  ISODD: 'number',
  ISTEXT: 'value',

  JOIN: 'delimiter, ignore_empty, text1, [text2], ...',

  LARGE: 'array, k',
  LEFT: 'text, [num_chars]',
  LEN: 'text',
  LET: 'name1, value1, calculation',
  LINEST: 'known_y\'s, [known_x\'s], [const], [stats]',
  LN: 'number',
  LOG: 'number, [base]',
  LOG10: 'number',
  LOOKUP: 'lookup_value, lookup_vector, [result_vector]',
  LOWER: 'text',

  MATCH: 'lookup_value, lookup_array, [match_type]',
  MAX: 'number1, [number2], ...',
  MAXIFS: 'max_range, criteria_range1, criteria1, ...',
  MEDIAN: 'number1, [number2], ...',
  MID: 'text, start_num, num_chars',
  MIN: 'number1, [number2], ...',
  MINIFS: 'min_range, criteria_range1, criteria1, ...',
  MINUTE: 'serial_number',
  MOD: 'number, divisor',
  MONTH: 'serial_number',
  MROUND: 'number, multiple',

  NA: '',
  NOW: '',
  NPV: 'rate, value1, [value2], ...',

  ODD: 'number',
  OFFSET: 'reference, rows, cols, [height], [width]',
  OR: 'logical1, [logical2], ...',

  PI: '',
  PMT: 'rate, nper, pv, [fv], [type]',
  POWER: 'number, power',
  PRODUCT: 'number1, [number2], ...',
  PROPER: 'text',

  RAND: '',
  RANDBETWEEN: 'bottom, top',
  'RANK.EQ': 'number, ref, [order]',
  RATE: 'nper, pmt, pv, [fv], [type], [guess]',
  RIGHT: 'text, [num_chars]',
  ROUND: 'number, num_digits',
  ROUNDDOWN: 'number, num_digits',
  ROUNDUP: 'number, num_digits',
  ROW: '[reference]',
  ROWS: 'array',

  SEARCH: 'find_text, within_text, [start_num]',
  SECOND: 'serial_number',
  SEQUENCE: 'rows, [columns], [start], [step]',
  SIN: 'number',
  SINH: 'number',
  SORT: 'array, [sort_index], [sort_order], [by_col]',
  SORTBY: 'array, by_array1, [sort_order1], ...',
  SQRT: 'number',
  'STDEV.P': 'number1, [number2], ...',
  'STDEV.S': 'number1, [number2], ...',
  SUBSTITUTE: 'text, old_text, new_text, [instance_num]',
  SUBTOTAL: 'function_num, ref1, [ref2], ...',
  SUM: 'number1, [number2], ...',
  SUMIF: 'range, criteria, [sum_range]',
  SUMIFS: 'sum_range, criteria_range1, criteria1, ...',
  SUMPRODUCT: 'array1, [array2], ...',
  SUMSQ: 'number1, [number2], ...',
  SWITCH: 'expression, value1, result1, [value2], [result2], ..., [default]',

  TAN: 'number',
  TANH: 'number',
  TEXT: 'value, format_text',
  TEXTJOIN: 'delimiter, ignore_empty, text1, [text2], ...',
  TIME: 'hour, minute, second',
  TODAY: '',
  TRIM: 'text',
  TRUE: '',
  TYPE: 'value',

  UNIQUE: 'array, [by_col], [exactly_once]',
  UPPER: 'text',

  VALUE: 'text',
  VLOOKUP: 'lookup_value, table_array, col_index_num, [range_lookup]',
  VSTACK: 'array1, [array2], ...',

  WEEKDAY: 'serial_number, [return_type]',
  WEEKNUM: 'serial_number, [return_type]',
  WORKDAY: 'start_date, days, [holidays]',
  WRAPROWS: 'vector, wrap_count, [pad_with]',
  WRAPCOLS: 'vector, wrap_count, [pad_with]',

  XLOOKUP: 'lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode]',
  XMATCH: 'lookup_value, lookup_array, [match_mode], [search_mode]',
  XOR: 'logical1, [logical2], ...',

  YEAR: 'serial_number',
};
